[www]

user = __USER_NAME__
group = __USER_NAME__

listen = 9000

listen.owner = __USER_NAME__
listen.group = __USER_NAME__

pm = dynamic

pm.max_children = 10
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3

clear_env = no